export const burger = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1351847788/photo/tilt-up-shot-of-a-grilled-beef-cheeseburger-with-french-fries.jpg?s=612x612&w=0&k=20&c=1qJwObkEcDa8Ir2PIVbYu1RIEr1969Lc5av95jOMzHw=",
        name: "Cheese Burger",
        price: "60",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1416033452/photo/cheeseburger-on-a-homemade-wooden-cutting-board-with-a-dark-background.jpg?s=612x612&w=0&k=20&c=DtiafCFiU08FdlxP4g4ZhhJAqeRuc7NGML4XWzPt--o=",
        name: "Veggie Burger",
        price: "80",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/186969620/photo/homemade-turkey-burger-on-a-bun-with-salad.jpg?s=612x612&w=0&k=20&c=I2i8NflckrXH1-_VH3NTZttib-RP4D5t1x9Qh-s-40U=",
        name: "Turkey Burger",
        price: "90",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/479335470/photo/homemade-organic-salmon-burger.jpg?s=612x612&w=0&k=20&c=6KUJHC4tpI7_bZhye5Gh3KrA4QyMEvOh-gdfmHYUC_I=",
        name: "Salmon Burger",
        price: "210",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1265242728/photo/crispy-chicken-burger-with-cheese-tomato-onions-and-lettuce.jpg?s=612x612&w=0&k=20&c=WRl1S0zNx1YeVOH6ceB92FN9STcsMB0F5xu-LlgfQ3M=",
        name: "Chicken Burger",
        price: "230",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/825626788/photo/beef-burger-with-cheddar-cheese-and-mushroom.jpg?s=612x612&w=0&k=20&c=CkyVkvUrLGdA6eUx2T5KU_bEgN28Ca6iAKtUJunvdw8=",
        name: "Mushroom",
        price: "260",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "burger",
        cartAdded: false,
    }
]