export const cake = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1158444054/photo/sliced-indulgent-chocolate-cake-against-a-rustic-aged-wooden-surface.jpg?s=612x612&w=0&k=20&c=tDO_iiJAdj57byptloLQr5qkSxJFaYB-T4fiXTWMxEw=",
        name: "Choclate Cake",
        price: "210",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1218487059/photo/fresh-fruit-cream-cake.jpg?s=612x612&w=0&k=20&c=HeTM_oneGotZ_BMDf08dV_F05SVS589XJtOFEH7wkG0=",
        name: "Fruit Cake",
        price: "230",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/615736056/photo/berry-pavlova-cake-with-strawberries-and-raspberries.jpg?s=612x612&w=0&k=20&c=y_S1Nw3e1gTnGsyBHFR56MCvWshQUhuUlJkUDECbV_w=",
        name: "Strawberry Cake",
        price: "260",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1278918978/photo/choco-chips-cake.jpg?s=612x612&w=0&k=20&c=nVcDeeEt6wbpJy5Lv8rsLj4wLk31DNRxAqVWfP5Zmpk=",
        name: "Blueberry Cake",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/521800053/photo/apple-pie-charlotte.jpg?s=612x612&w=0&k=20&c=sZXa25lklghhCgwZU_IWU4psQCJcuyRV5m7Jr4OicGI=",
        name: "Apple Cake",
        price: "220",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1265436356/photo/butterscotch-cake.jpg?s=612x612&w=0&k=20&c=5llGKDRjPm1cGXERqT-WtfAaT5BtWjSuSxk100Rjv1w=",
        name: "Butterscotch Cake",
        price: "290",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1328701743/photo/caramelised-pineapple-upside-down-cake-home-baked-pineapple-cake-with-pineapple-slices-are-on.jpg?s=612x612&w=0&k=20&c=ySom34Pw-PRMT-W_ac3zkv-KqGUxhkhj3AI5adIySpg=",
        name: "Pineapple Cake",
        price: "330",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "cake",
        cartAdded: false,
    },
]