export const chocolate = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/458614037/photo/cadbury-dairy-milk-chocolate-bar.jpg?s=612x612&w=0&k=20&c=Q7j3252AXKQbSMkoR-SkaL8MIZbVt7JyjVY7zKabF_M=",
        name: "Cadbury",
        price: "30",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/458696609/photo/kit-kat-nestle-chocolate-bars.jpg?s=612x612&w=0&k=20&c=tMpwNk4GTYS5tgBQPY-w0ZOwFMTF41Csonuivxoyv48=",
        name: "Kit Kat",
        price: "40",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/836622166/photo/cut-chocolate-candy-with-vanilla-and-chocolate-ganache.jpg?s=612x612&w=0&k=20&c=Yu-cT32_FxM3QszPBy86GC0xHxqdgwT7M9iPOf4wmvc=",
        name: "Flaneur Chocolate",
        price: "60",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1225394492/photo/image-of-baked-homemade-carrot-coconut-and-chocolate-chip-cookies-drizzled-with-dark.jpg?s=612x612&w=0&k=20&c=ohOT-YbYeLCdQx6n95xD0P2LY3f-q8LFzaypLz0z84c=",
        name: "Savour Chocolate",
        price: "80",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1146718468/photo/stack-of-assorted-donuts-copy-space.jpg?s=612x612&w=0&k=20&c=uIurkD1otLyiXC_siu1m3cVcujkebcbn2ZbOuLyDNK0=",
        name: "Donut",
        price: "90",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/183255573/photo/chocolate-collection-on-a-silk-ackground.jpg?s=612x612&w=0&k=20&c=T31GOgn4FL9Z0pP9MDWcSiexWJ68MjEj2jCDox7jBqw=",
        name: "Fabelle",
        price: "99",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "chocolate",
        cartAdded: false,
    },
]