export const food = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1264335504/photo/image-of-greek-salad-patterned-bowl-side-dishes-of-chopped-cherry-tomatoes-and-feta-cheese.jpg?s=612x612&w=0&k=20&c=Rd6ETFFXWmPGLgaKGMAZagXJa-UZRS_xcT19CeJVhqY=",
        name: "Greek Salad",
        price: "790",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/801087100/photo/kachumber-or-indian-green-salad-served-in-red-or-white-bowl-selective-focus.jpg?s=612x612&w=0&k=20&c=yUt4_nae_jKU5TNiN3DDNFesSXW6NgytDLIDRLLmdV4=",
        name: "Veg Salad",
        price: "865",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/169986941/photo/chicken-salad.jpg?s=612x612&w=0&k=20&c=mhlPogSGJelbx8fJTwn7sNpH8a7f_tFVrj7VWLnKYVY=",
        name: "Chicken Salad",
        price: "980",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/185099519/photo/spring-salad.jpg?s=612x612&w=0&k=20&c=PC6CjFlr7MD_rGNN-eobQF-fMjdMymwdYGzGIZtGzAY=",
        name: "Clover Salad",
        price: "999",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/535983647/photo/lasagna-rolls-with-tomato-sauce.jpg?s=612x612&w=0&k=20&c=radEhFoyEFpq4zCQ74XAcGuEGO9kkAyWncKsU5cMjc8=",
        name: "Lasagna Rolls",
        price: "1199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1409919858/photo/delicious-indian-street-food-egg-rolls-is-ready-to-eat.jpg?s=612x612&w=0&k=20&c=7b-uTwR8qmESV_nP3Rsh4qqKCay4vsG_B7j0UhaMFPY=",
        name: "Peri Peri Rolls",
        price: "1388",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1024561236/photo/indian-veg-chapati-wrap-kathi-roll-served-in-a-plate-with-sauce-over-moody-background.jpg?s=612x612&w=0&k=20&c=S8hp5HNMkAy2Pg6uqzhMd5llleMOea1WpA3_SAORAb8=",
        name: "Veg Rolls",
        price: "799",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "food",
        cartAdded: false,
    },
]