export const noodles = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1322237940/photo/cooking-indian-style-vegetable-maggie-noodles-at-home.jpg?s=612x612&w=0&k=20&c=fy33CnUiHa5R-aeQAauLJj_q8virzgw4QYj7pJNYN04=",
        name: "Maggie",
        price: "40",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1497708305/photo/noodles-and-veg-manchurian-in-a-bowl-food-stock-photo.jpg?s=612x612&w=0&k=20&c=1EwLtKnuFSO3xmkyg_589xy_tBKPqWCRxWwBEsh6qxw=",
        name: "Hot Dry Noodles",
        price: "80",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1365977387/photo/ramen-with-steaming-sizzle.jpg?s=612x612&w=0&k=20&c=8-Dij3YocgfVa2kj37msXT_iqzIgbqq0Ta3c1G4_-A0=",
        name: "Ramen",
        price: "90",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/483137365/photo/asian-chow-mein-noodles.jpg?s=612x612&w=0&k=20&c=aVkPKpDkiAM7CxTFinQBax0i-nm-ybzWimrJRyPePcg=",
        name: "Chow Mein",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1309506339/photo/thai-food.jpg?s=612x612&w=0&k=20&c=8jC1ess9C8GzFzIkSS-QS0h5w_9bkyVaG7VX2_QS4S4=",
        name: "Khao Soi",
        price: "220",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/2152450317/photo/sphagetti-and-meatball.jpg?s=612x612&w=0&k=20&c=HsdcqV7tKV2FcCAoQLwa_Qnbfq-diqR4MxdiNd96Esw=",
        name: "Sphagetti",
        price: "120",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "noodles",
        cartAdded: false,
    },
]