export const pasta = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/183869552/photo/pasta-with-king-prawns.jpg?s=612x612&w=0&k=20&c=aLTrQ16nUuIEnoP6_haHbJ9ZZMjV7xyuhIBPG4ipFeo=",
        name: "Linguine",
        price: "255",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1018825988/photo/macaroni-and-cheese-with-tomato-sauce.jpg?s=612x612&w=0&k=20&c=yaoX1vZCjuXLLK90TBpqniF1Xtz1zI3PaCWDrxgy6M4=",
        name: "Macaroni",
        price: "160",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/155433175/photo/penne-tomato-and-basil.jpg?s=612x612&w=0&k=20&c=90Dpmg9cTCV4Wl3HNYDx3h-n3kzfCBNPQBUp3CJrjtc=",
        name: "Penne",
        price: "180",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1179014929/photo/cheesy-pasta-skillet.jpg?s=612x612&w=0&k=20&c=Ls5hJnWXZsYaTRcgZT5f3-IesZWCzo_wKzsCeNvohcU=",
        name: "Fusilli",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1276816070/photo/rigatoni-pasta-with-tomato-sauce-garnished-with-fresh-parsley-and-cheese.jpg?s=612x612&w=0&k=20&c=TDFBvjG4g-5CTgWsZeJKUrBhtyqWOO2qv10ctj_qru4=",
        name: "Rigatoni",
        price: "230",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/2152450317/photo/sphagetti-and-meatball.jpg?s=612x612&w=0&k=20&c=HsdcqV7tKV2FcCAoQLwa_Qnbfq-diqR4MxdiNd96Esw=",
        name: "Sphagetti",
        price: "120",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pasta",
        cartAdded: false,
    },
]