export const pizza = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1269122740/photo/pizza-with-very-much-cheese-melting.jpg?s=612x612&w=0&k=20&c=61EQYbnkiUaH64gdiCtnExqIn4f84i6GhBJtQ9NGdPk=",
        name: "Cheese Pizza",
        price: "130",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/2150383746/photo/food-photos-various-entrees-appetizers-deserts-etc.jpg?s=612x612&w=0&k=20&c=Wotwv3RdBzDmgijx4ujP44aaC6GF53bleATVcLFRqO0=",
        name: "Veggie Pizza",
        price: "165",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1387688651/photo/cheese-capsicum-onion-pizza.jpg?s=612x612&w=0&k=20&c=MHUnHHOAl7aABTzCFHHSkAwacW9DeoB6_69QKPCKCPQ=",
        name: "Pepperoni Pizza",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1414575281/photo/a-delicious-and-tasty-italian-pizza-margherita-with-tomatoes-and-buffalo-mozzarella.jpg?s=612x612&w=0&k=20&c=v8mdiAa_5NaRYtIscClXe85lLzkx7loSd9_pJWt9G2o=",
        name: "Margherita Pizza",
        price: "210",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1388938025/photo/pan-pizza-freshly-baked-with-lot-of-cheese-and-vegetable-and-paneer.jpg?s=612x612&w=0&k=20&c=Pjl4o6US2UWdtHKjOOaEY6_FtFB7U8zaTXMd8E9re_M=",
        name: "Paneer Pizza",
        price: "230",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/484811667/photo/homemade-barbecue-chicken-pizza.jpg?s=612x612&w=0&k=20&c=-gI_6ARm7wl-AIQLVOYP6dgVNGjdiX7PHrzR2CA3C_w=",
        name: "BBQ Chicken",
        price: "260",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/537640710/photo/homemade-pineapple-and-ham-hawaiian-pizza.jpg?s=612x612&w=0&k=20&c=j2aAIbK9Emya9FHhBgBXG38DhC0vVGSdqK5FcsbZDHY=",
        name: "Hawaiian Pizza",
        price: "299",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "pizza",
        cartAdded: false,
    },
]