export const rolls = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/535983647/photo/lasagna-rolls-with-tomato-sauce.jpg?s=612x612&w=0&k=20&c=radEhFoyEFpq4zCQ74XAcGuEGO9kkAyWncKsU5cMjc8=",
        name: "Lasagna Rolls",
        price: "1199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1409919858/photo/delicious-indian-street-food-egg-rolls-is-ready-to-eat.jpg?s=612x612&w=0&k=20&c=7b-uTwR8qmESV_nP3Rsh4qqKCay4vsG_B7j0UhaMFPY=",
        name: "Peri Peri Rolls",
        price: "1388",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1024561236/photo/indian-veg-chapati-wrap-kathi-roll-served-in-a-plate-with-sauce-over-moody-background.jpg?s=612x612&w=0&k=20&c=S8hp5HNMkAy2Pg6uqzhMd5llleMOea1WpA3_SAORAb8=",
        name: "Veg Rolls",
        price: "799",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1438449132/photo/egg-cheese-chicken-burger-shawarma-wrap-with-salad-dip-and-sauce-isolated-wooden-board-side.jpg?s=612x612&w=0&k=20&c=o34qlfaytv5yfsxdmaWNdU6u524cGl3NXn-X5fjAFdY=",
        name: "Potato Rolls",
        price: "499",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1209898811/photo/chapati-wrap-with-cheese-vegetarian-food.jpg?s=612x612&w=0&k=20&c=nSbQOQrOq4W2VDYlazvsX9BERrqPekAM5KIEMf0kwCU=",
        name: "Paneer Rolls",
        price: "599",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/134149993/photo/egg-rolls.jpg?s=612x612&w=0&k=20&c=H3k7A7R8GR8wpncYrl3-0AE99X_dbp57xlyg8ba__Ko=",
        name: "Tikki Rolls",
        price: "530",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "rolls",
        cartAdded: false,
    },
]