export const sandwich = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/184338592/photo/grilled-cheese-sandwich-with-ketchup.jpg?s=612x612&w=0&k=20&c=9akRyWaT7n_-40nap4Qh7kdZrtzO0tJwL4rSs3skHMI=",
        name: "Grilled Cheese",
        price: "175",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1079003392/photo/cheese-toast.jpg?s=612x612&w=0&k=20&c=vsugRVfW3JRaQQZOH6hiYOA1IID-H2rva2ek1IIOdBo=",
        name: "Cheese sandwich",
        price: "299",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1085141418/photo/paneer-tikka-sandwich-is-a-popular-indian-version-of-sandwich-using-cottage-cheese-curry-with.jpg?s=612x612&w=0&k=20&c=DmNP5IGd4E9CQi9TfkQqHQ8riYw-PtNr6lqf-C5KuW4=",
        name: "Paneer Sandwich",
        price: "220",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/881781266/photo/vegetarian-quesadilla-with-vegetables-and-cheese-in-cast-iron-frying-pan.jpg?s=612x612&w=0&k=20&c=gbudxAiJvsitOGmVn0Wi8EMicuw-JBXBQiHC6idbUh8=",
        name: "Corn Sandwich",
        price: "240",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1388378926/photo/philly-cheesesteak-sandwich-and-french-fries.jpg?s=612x612&w=0&k=20&c=9OJs3TfL2jbdkxJ2bHVlOv-jQdGvtCyi_ol2MlLPYdY=",
        name: "Cheese Steak",
        price: "185",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1300443216/photo/vegetable-paneer-sandwich-using-cottage-cheese-with-tomato-onion-and-lettuce-with-chutney.jpg?s=612x612&w=0&k=20&c=3oF8PsUvInw4lLYe6JGYdz65_bYzfrPKLu-SYwa4AaI=",
        name: "Veg Sandwich",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/685523376/photo/white-bread-chicken-and-mayonnaise-sandwich.jpg?s=612x612&w=0&k=20&c=DuQPvdFfTdRB7pXRbmFF014LNWfuwR9NXnGrgkPsW2A=",
        name: "Mayonnaise",
        price: "199",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere eos reiciendis, necessitatibus eius expedita totam sequi esse, officiis asperiores magni dignissimos.",
        quantity: 1,
        category: "sandwich",
        cartAdded: false,
    },
]